xcodeproj 'BasicLocalizer'

target 'BasicLocalizer' do
  platform :osx, '10.10'
  pod 'OpenCV', :podspec => '../../platform/ios/podspecs/OpenCV.podspec'
  pod 'boost', :podspec => '../../platform/ios/podspecs/boost.podspec.json'
  pod 'eigen', :podspec => '../../platform/ios/podspecs/eigen.podspec.json'
  pod 'picojson', :podspec => '../../platform/ios/podspecs/picojson.podspec'
  pod 'cereal', :podspec => '../../platform/ios/podspecs/cereal.podspec'
end


target 'BasicLocalizerTest' do
  platform :osx, '10.10'
  pod 'boost', :podspec => '../../platform/ios/podspecs/boost.podspec.json'
  pod 'eigen', :podspec => '../../platform/ios/podspecs/eigen.podspec.json'
  pod 'picojson', :podspec => '../../platform/ios/podspecs/picojson.podspec'
  pod 'cereal', :podspec => '../../platform/ios/podspecs/cereal.podspec'
end
