project 'bleloc'

target 'bleloc' do
  use_frameworks!
  platform :ios, '9.0'
  pod 'OpenCV', :podspec => './podspecs/OpenCV.podspec'
  pod 'boost', :podspec => './podspecs/boost.podspec.json'
  pod 'eigen', :podspec => './podspecs/eigen.podspec.json'
  pod 'picojson', :podspec => './podspecs/picojson.podspec'
  pod 'cereal', :podspec => './podspecs/cereal.podspec'
end
target 'blelocjni' do
  platform :osx
  pod 'boost', :podspec => './podspecs/boost.podspec.json'
  pod 'eigen', :podspec => './podspecs/eigen.podspec.json'
  pod 'picojson', :podspec => './podspecs/picojson.podspec'
  pod 'cereal', :podspec => './podspecs/cereal.podspec'
end

