xcodeproj 'CnnLocalizer'

target 'CnnBasicLocalizer' do
  platform :osx
  pod 'boost', :podspec => '../../platform/ios/podspecs/boost.podspec.json'
  pod 'eigen', '3.2.5'
  pod 'picojson', :podspec => '../../platform/ios/podspecs/picojson.podspec'
  pod 'cereal', :podspec => '../../platform/ios/podspecs/cereal.podspec'
end

target 'CnnManagerTest' do
  platform :osx
  pod 'boost', :podspec => '../../platform/ios/podspecs/boost.podspec.json'
  pod 'eigen', '3.2.5'
  pod 'picojson', :podspec => '../../platform/ios/podspecs/picojson.podspec'
  pod 'cereal', :podspec => '../../platform/ios/podspecs/cereal.podspec'
end
