xcodeproj 'AnchorConverter'

target 'AnchorConverter' do
  platform :osx
  pod 'boost', :podspec => '../../platform/ios/podspecs/boost.podspec.json'
  pod 'eigen'
  pod 'picojson', :podspec => '../../platform/ios/podspecs/picojson.podspec'
  pod 'cereal', :podspec => '../../platform/ios/podspecs/cereal.podspec'
end

